-- DIVYANGSATHI WEBSITE CMS - run once in Supabase SQL Editor
create extension if not exists pgcrypto;
create or replace function public.is_active_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admins where id=auth.uid() and active=true); $$;
create table if not exists public.cms_page_overrides(id uuid primary key default gen_random_uuid(),page_slug text not null,selector text not null,property text not null default 'text',value text,status text not null default 'draft' check(status in('draft','published')),sort_order int not null default 0,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_menu_items(id uuid primary key default gen_random_uuid(),location text not null default 'header',label text not null,url text not null,icon text,sort_order int default 0,is_visible boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_theme(id uuid primary key default gen_random_uuid(),name text not null,settings jsonb not null default '{}'::jsonb,is_active boolean default false,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_seo(id uuid primary key default gen_random_uuid(),page_slug text not null unique,title text,description text,keywords text,canonical_url text,og_image_url text,robots text default 'index,follow',created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_notifications(id uuid primary key default gen_random_uuid(),title text not null,message text not null,image_url text,button_text text,button_url text,priority int default 0,status text default 'draft' check(status in('draft','published')),starts_at timestamptz default now(),ends_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_media(id uuid primary key default gen_random_uuid(),name text not null,type text default 'image',url text not null,alt_text text,category text,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_services(id uuid primary key default gen_random_uuid(),type text default 'service',name text not null,description text,image_url text,sort_order int default 0,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_documents(id uuid primary key default gen_random_uuid(),title text not null,category text,url text not null,status text default 'draft',created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.cms_settings(id uuid primary key default gen_random_uuid(),key text not null unique,value jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
-- RLS: public can read only live content; active admins can manage all CMS records.
do $$ declare t text; begin foreach t in array array['cms_page_overrides','cms_menu_items','cms_theme','cms_seo','cms_notifications','cms_media','cms_services','cms_documents','cms_settings'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists cms_admin_all on public.%I',t); execute format('create policy cms_admin_all on public.%I for all to authenticated using (public.is_active_admin()) with check (public.is_active_admin())',t); end loop; end $$;
drop policy if exists cms_public_pages on public.cms_page_overrides; create policy cms_public_pages on public.cms_page_overrides for select to anon,authenticated using(deleted_at is null and status='published');
drop policy if exists cms_public_theme on public.cms_theme; create policy cms_public_theme on public.cms_theme for select to anon,authenticated using(deleted_at is null and is_active=true);
drop policy if exists cms_public_notifications on public.cms_notifications; create policy cms_public_notifications on public.cms_notifications for select to anon,authenticated using(deleted_at is null and status='published' and starts_at<=now() and (ends_at is null or ends_at>=now()));
drop policy if exists cms_public_menu on public.cms_menu_items; create policy cms_public_menu on public.cms_menu_items for select to anon,authenticated using(deleted_at is null and is_visible=true);
drop policy if exists cms_public_seo on public.cms_seo; create policy cms_public_seo on public.cms_seo for select to anon,authenticated using(deleted_at is null);
drop policy if exists cms_public_services on public.cms_services; create policy cms_public_services on public.cms_services for select to anon,authenticated using(deleted_at is null and is_active=true);
drop policy if exists cms_public_documents on public.cms_documents; create policy cms_public_documents on public.cms_documents for select to anon,authenticated using(deleted_at is null and status='published');
create or replace view public.cms_trash_view as select 'cms_page_overrides'::text source_table,id,(page_slug||' · '||selector)::text label,deleted_at from public.cms_page_overrides where deleted_at is not null union all select 'cms_menu_items',id,label,deleted_at from public.cms_menu_items where deleted_at is not null union all select 'cms_notifications',id,title,deleted_at from public.cms_notifications where deleted_at is not null union all select 'cms_media',id,name,deleted_at from public.cms_media where deleted_at is not null union all select 'cms_services',id,name,deleted_at from public.cms_services where deleted_at is not null union all select 'cms_documents',id,title,deleted_at from public.cms_documents where deleted_at is not null union all select 'cms_seo',id,page_slug,deleted_at from public.cms_seo where deleted_at is not null;
grant select on public.cms_trash_view to authenticated;
