-- DivyangSathi FINAL CMS extension: Website Theme Manager + independent Admin CMS
create extension if not exists pgcrypto;
create table if not exists public.cms_theme_history(id uuid primary key default gen_random_uuid(),theme_data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.admin_cms_overrides(id uuid primary key default gen_random_uuid(),page_slug text not null,selector text not null,property text not null,value text,status text not null default 'published',sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists public.admin_cms_menu(id uuid primary key default gen_random_uuid(),label text not null,icon text,url text not null,sort_order int not null default 0,is_visible boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table if not exists public.admin_cms_themes(id uuid primary key default gen_random_uuid(),name text not null,settings jsonb not null default '{}'::jsonb,is_active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
alter table public.admin_cms_overrides enable row level security; alter table public.admin_cms_menu enable row level security; alter table public.admin_cms_themes enable row level security; alter table public.cms_theme_history enable row level security;
do $$ declare t text; begin foreach t in array array['admin_cms_overrides','admin_cms_menu','admin_cms_themes','cms_theme_history'] loop execute format('drop policy if exists %I on public.%I','admin_all_'||t,t); execute format('create policy %I on public.%I for all to authenticated using (exists(select 1 from public.admins a where a.id=auth.uid() and a.active=true)) with check (exists(select 1 from public.admins a where a.id=auth.uid() and a.active=true))','admin_all_'||t,t); end loop; end $$;
-- Public/authenticated read is required for admin runtime after admin login.
drop policy if exists admin_runtime_read_overrides on public.admin_cms_overrides; create policy admin_runtime_read_overrides on public.admin_cms_overrides for select to authenticated using (deleted_at is null and status='published');
drop policy if exists admin_runtime_read_themes on public.admin_cms_themes; create policy admin_runtime_read_themes on public.admin_cms_themes for select to authenticated using (deleted_at is null);
